development:
  adapter: postgresql
  encoding: unicode
  database: cpp_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: cpp_test
<% if ENV["TRAVIS"] %>
  username: postgres
<% end %>
  pool: 5
